// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRF6Gw0BNK4vPyW7rnITySOWXsMFhx6FE',
    appId: '1:1091837167475:web:17437076b0618ac59f2706',
    messagingSenderId: '1091837167475',
    projectId: 'musicapp-46209',
    authDomain: 'musicapp-46209.firebaseapp.com',
    storageBucket: 'musicapp-46209.firebasestorage.app',
    measurementId: 'G-9LL39P6Z59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwh0mLb_YFOiZs-2rd2OE5o6V2CWi48c',
    appId: '1:1091837167475:android:dea4cbba4a0062df9f2706',
    messagingSenderId: '1091837167475',
    projectId: 'musicapp-46209',
    storageBucket: 'musicapp-46209.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR10QaN8dXRjnS58VJZcIhe814ewmyqh0',
    appId: '1:1091837167475:ios:86d4aa19f05fdf5b9f2706',
    messagingSenderId: '1091837167475',
    projectId: 'musicapp-46209',
    storageBucket: 'musicapp-46209.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR10QaN8dXRjnS58VJZcIhe814ewmyqh0',
    appId: '1:1091837167475:ios:86d4aa19f05fdf5b9f2706',
    messagingSenderId: '1091837167475',
    projectId: 'musicapp-46209',
    storageBucket: 'musicapp-46209.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRF6Gw0BNK4vPyW7rnITySOWXsMFhx6FE',
    appId: '1:1091837167475:web:0abfa105f554ca7b9f2706',
    messagingSenderId: '1091837167475',
    projectId: 'musicapp-46209',
    authDomain: 'musicapp-46209.firebaseapp.com',
    storageBucket: 'musicapp-46209.firebasestorage.app',
    measurementId: 'G-RJTGDZQCJG',
  );
}
